language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: jvrlFTT1Ug6c9vgZuaz8IoK7yzopWm7Ue+c+1yFOgP7mCttAOGyc2UlBdUdECXfkyrXwCL0cgI07MIb8jlzDNrgtsKxbWvpAkec1/z1nlEE7nrq92q1CX+TZpzVuVO5P8BFnmSpzqPmZBX7Z/84z7wkItMN3VJt1ZQZi0x1ZaIk=
  - secure: DBGgKqMCi5Y8SokoSxqPI872UCDSA7/ynE+jAEFzFUrKmfBgYXXvwUWJvlcIAMcg+EGAywfloOUEvx7qyWt8qDZxOCsI0MmIUB+GP/k1nMzthkUtwUa9kABQSl/ekctfy9NqzKZuEE8CyF8MyjXaQ2gpOyIEGrx0t8iA32/DKsk=
